/* =====================================================================
   CLIMA MARKT — product catalog
   Each product is presented as a supermarket item: barcode, price,
   energy label and key specifications. The `photo` field is null here;
   drop in a real image URL to blend real product photography with the
   procedural 3D packaging. `kind` drives the SVG illustration and the
   3D package accent.
   ===================================================================== */

const STORE = {
  name: 'CLIMA MARKT',
  tagline: 'Air & Ventilation Supermarket',
  address: 'Koelstraat 21 · 7511 AB Enschede',
  kvk: 'KVK 8842 1190',
  btw: 'BTW NL0042.18.221.B01',
  phone: '+31 53 123 45 67',
  email: 'verkoop@climamarkt.nl',
  vatRate: 0.21,
};

/* Energy ratings use the EU ladder A (best) → G (worst). */
const ENERGY_SCALE = ['A', 'B', 'C', 'D', 'E', 'F', 'G'];

const PRODUCTS = [
  /* ------------------------- FEATURED SPLIT AC ----------------------- */
  {
    id: 'ac-arctic-pro',
    name: 'ArcticPro 3.5kW Split',
    brand: 'NORDLUFT',
    category: 'featured',
    kind: 'split',
    price: 749.0,
    rating: 'A',
    color: '#3aa6e0',
    barcode: '8710421003051',
    badge: 'BESTSELLER',
    photo: null,
    specs: {
      'Cooling capacity': '3.5 kW (12.000 BTU)',
      'Coverage': 'up to 35 m²',
      'Noise level': '19 dB(A)',
      'SEER': '7.4',
      'Refrigerant': 'R32 · eco',
      'Wifi control': 'Yes — app & voice',
    },
    features: ['Inverter', 'Wifi + App', 'Self-clean', 'Heat pump'],
  },
  {
    id: 'ac-polar-x',
    name: 'PolarX 5.0kW Split',
    brand: 'NORDLUFT',
    category: 'featured',
    kind: 'split',
    price: 1049.0,
    rating: 'A',
    color: '#1d7fb8',
    barcode: '8710421005024',
    badge: 'PREMIUM',
    photo: null,
    specs: {
      'Cooling capacity': '5.0 kW (18.000 BTU)',
      'Coverage': 'up to 55 m²',
      'Noise level': '21 dB(A)',
      'SEER': '8.1',
      'Refrigerant': 'R32 · eco',
      'Wifi control': 'Yes — app & voice',
    },
    features: ['Inverter', 'Wifi + App', 'Turbo cool', 'Heat pump'],
  },
  {
    id: 'ac-breeze-duo',
    name: 'Breeze Duo Multi-Split',
    brand: 'AIRO',
    category: 'featured',
    kind: 'split',
    price: 1399.0,
    rating: 'B',
    color: '#2bb3c0',
    barcode: '8710421007028',
    badge: 'MULTI-ROOM',
    photo: null,
    specs: {
      'Cooling capacity': '2× 2.6 kW',
      'Coverage': '2 rooms · 50 m²',
      'Noise level': '22 dB(A)',
      'SEER': '6.9',
      'Refrigerant': 'R32 · eco',
      'Wifi control': 'Yes — per unit',
    },
    features: ['Dual zone', 'Inverter', 'Wifi + App', 'Sleep mode'],
  },

  /* ------------------------- VENTILATION ----------------------------- */
  {
    id: 'vent-flow-hrv',
    name: 'FlowMaster HRV 400',
    brand: 'VENTA',
    category: 'ventilation',
    kind: 'ventilation',
    price: 1289.0,
    rating: 'A',
    color: '#4cb5e8',
    barcode: '8710421101015',
    badge: 'HEAT RECOVERY',
    photo: null,
    specs: {
      'Airflow': '400 m³/h',
      'Heat recovery': '92%',
      'Coverage': 'whole home',
      'Noise level': '24 dB(A)',
      'Filter': 'F7 + carbon',
      'Wifi control': 'Yes — CO₂ auto',
    },
    features: ['Heat recovery', 'CO₂ sensor', 'Silent', 'F7 filter'],
  },
  {
    id: 'vent-duct-q',
    name: 'DuctLine Q Inline Fan',
    brand: 'VENTA',
    category: 'ventilation',
    kind: 'ventilation',
    price: 219.0,
    rating: 'B',
    color: '#3aa6e0',
    barcode: '8710421102029',
    badge: null,
    photo: null,
    specs: {
      'Airflow': '180 m³/h',
      'Duct size': 'Ø 125 mm',
      'Coverage': 'kitchen / bath',
      'Noise level': '28 dB(A)',
      'Filter': 'washable mesh',
      'Wifi control': 'optional module',
    },
    features: ['Inline', 'Low noise', 'Easy fit', 'Humidity stat'],
  },
  {
    id: 'vent-extract-eco',
    name: 'EcoExtract Bathroom',
    brand: 'AIRO',
    category: 'ventilation',
    kind: 'ventilation',
    price: 89.0,
    rating: 'A',
    color: '#5cc0d6',
    barcode: '8710421103033',
    badge: 'VALUE',
    photo: null,
    specs: {
      'Airflow': '95 m³/h',
      'Duct size': 'Ø 100 mm',
      'Coverage': 'bathroom / wc',
      'Noise level': '26 dB(A)',
      'Filter': '—',
      'Wifi control': 'no',
    },
    features: ['Timer', 'Humidity stat', 'Backdraft shutter', 'Quiet'],
  },

  /* ------------------------- PORTABLE AC ----------------------------- */
  {
    id: 'port-nomad-9',
    name: 'Nomad 9K Portable',
    brand: 'AIRO',
    category: 'portable',
    kind: 'portable',
    price: 329.0,
    rating: 'A',
    color: '#3aa6e0',
    barcode: '8710421201019',
    badge: 'PLUG & COOL',
    photo: null,
    specs: {
      'Cooling capacity': '2.6 kW (9.000 BTU)',
      'Coverage': 'up to 25 m²',
      'Noise level': '54 dB(A)',
      'EER': '2.6',
      'Refrigerant': 'R290 · eco',
      'Wifi control': 'Yes — app',
    },
    features: ['No install', 'Wheels', 'App', 'Dehumidify'],
  },
  {
    id: 'port-nomad-12',
    name: 'Nomad 12K Portable',
    brand: 'AIRO',
    category: 'portable',
    kind: 'portable',
    price: 449.0,
    rating: 'A',
    color: '#1d7fb8',
    barcode: '8710421202023',
    badge: null,
    photo: null,
    specs: {
      'Cooling capacity': '3.5 kW (12.000 BTU)',
      'Coverage': 'up to 35 m²',
      'Noise level': '56 dB(A)',
      'EER': '2.8',
      'Refrigerant': 'R290 · eco',
      'Wifi control': 'Yes — app',
    },
    features: ['No install', 'Wheels', 'App', '3-in-1'],
  },
  {
    id: 'port-mistcube',
    name: 'MistCube Evaporative',
    brand: 'KOELO',
    category: 'portable',
    kind: 'portable',
    price: 159.0,
    rating: 'A',
    color: '#2bb3c0',
    barcode: '8710421203030',
    badge: 'LOW WATT',
    photo: null,
    specs: {
      'Cooling capacity': 'evaporative',
      'Coverage': 'up to 18 m²',
      'Noise level': '48 dB(A)',
      'Power': '65 W',
      'Tank': '7 L',
      'Wifi control': 'no',
    },
    features: ['65 W only', 'Ice tray', '3 speeds', 'Oscillation'],
  },

  /* ------------------------- CEILING & STANDING FANS ----------------- */
  {
    id: 'fan-halo-ceiling',
    name: 'Halo DC Ceiling Fan',
    brand: 'KOELO',
    category: 'fans',
    kind: 'fan-ceiling',
    price: 199.0,
    rating: 'A',
    color: '#4cb5e8',
    barcode: '8710421301013',
    badge: 'DC MOTOR',
    photo: null,
    specs: {
      'Blade span': '132 cm',
      'Airflow': '11.000 m³/h',
      'Noise level': '32 dB(A)',
      'Power': '6–35 W (DC)',
      'Light': 'integrated LED',
      'Wifi control': 'Yes — remote + app',
    },
    features: ['DC motor', 'Remote', 'LED light', '6 speeds'],
  },
  {
    id: 'fan-tower-breeze',
    name: 'Tower Breeze Standing',
    brand: 'KOELO',
    category: 'fans',
    kind: 'fan-stand',
    price: 119.0,
    rating: 'A',
    color: '#3aa6e0',
    barcode: '8710421302027',
    badge: null,
    photo: null,
    specs: {
      'Height': '102 cm',
      'Airflow': '2.400 m³/h',
      'Noise level': '36 dB(A)',
      'Power': '45 W',
      'Oscillation': '80°',
      'Wifi control': 'remote',
    },
    features: ['Oscillation', 'Remote', 'Timer', '3 speeds'],
  },
  {
    id: 'fan-bladeless-air',
    name: 'PureAir Bladeless',
    brand: 'NORDLUFT',
    category: 'fans',
    kind: 'fan-stand',
    price: 249.0,
    rating: 'A',
    color: '#1d7fb8',
    barcode: '8710421303031',
    badge: 'PURIFY',
    photo: null,
    specs: {
      'Height': '95 cm',
      'Airflow': '1.900 m³/h',
      'Noise level': '34 dB(A)',
      'Power': '40 W',
      'Filter': 'HEPA + carbon',
      'Wifi control': 'Yes — app',
    },
    features: ['Bladeless', 'HEPA purify', 'App', 'Night mode'],
  },
];

const CATEGORIES = [
  { id: 'featured', label: 'Featured Air Conditioners', tag: 'SPLIT SYSTEMS', icon: 'snow' },
  { id: 'ventilation', label: 'Ventilation Systems', tag: 'AIR EXCHANGE', icon: 'wind' },
  { id: 'portable', label: 'Portable Air Conditioners', tag: 'PLUG & COOL', icon: 'plug' },
  { id: 'fans', label: 'Ceiling & Standing Fans', tag: 'AIRFLOW', icon: 'fan' },
];

const SERVICES = [
  {
    id: 'svc-install',
    name: 'Installation',
    icon: 'tools',
    from: 295,
    desc: 'Certified F-gas engineers. Wall mount, vacuum, gas check & commissioning.',
    points: ['F-gas certified', 'Within 10 working days', '5-year workmanship'],
  },
  {
    id: 'svc-maintenance',
    name: 'Maintenance Plan',
    icon: 'shield',
    from: 89,
    desc: 'Yearly clean, filter swap, gas-pressure check and efficiency report.',
    points: ['Annual visit', 'Filters included', 'Priority callout'],
  },
  {
    id: 'svc-repair',
    name: 'Repair & Diagnostics',
    icon: 'wrench',
    from: 65,
    desc: 'Fault finding, leak detection and parts replacement for all major brands.',
    points: ['All brands', 'Leak detection', 'Genuine parts'],
  },
  {
    id: 'svc-advice',
    name: 'Free Site Survey',
    icon: 'clipboard',
    from: 0,
    desc: 'On-site measurement and a tailored quotation — no obligation.',
    points: ['No obligation', 'Heat-load calc', 'Same-week visit'],
  },
];

const REVIEWS = [
  {
    name: 'Marloes V.',
    place: 'Enschede',
    stars: 5,
    date: '2026-05-18',
    text: 'The ArcticPro keeps our whole living room at 21° silently. Install team was in and out in three hours. Receipt-style invoice was a nice touch!',
    product: 'ArcticPro 3.5kW',
  },
  {
    name: 'Daan K.',
    place: 'Hengelo',
    stars: 5,
    date: '2026-04-30',
    text: 'Ordered the FlowMaster HRV after the free survey. CO₂ levels dropped instantly and the heat recovery is paying for itself.',
    product: 'FlowMaster HRV 400',
  },
  {
    name: 'Priya S.',
    place: 'Almelo',
    stars: 4,
    date: '2026-06-02',
    text: 'Portable Nomad 12K was plug-and-play for my home office. App control is genuinely useful. Only wish it were a touch quieter at night.',
    product: 'Nomad 12K Portable',
  },
  {
    name: 'Tom B.',
    place: 'Oldenzaal',
    stars: 5,
    date: '2026-03-21',
    text: 'The Halo ceiling fan looks premium and the DC motor sips power. Maintenance plan means I never think about it. Top supermarket-of-climate concept.',
    product: 'Halo DC Ceiling Fan',
  },
];
